import { reactive } from "vue";

export const store = reactive({
  apiUrl: "https://api.themoviedb.org/3/",
  endPoint: {
    movie: "search/movie",
    series: "search/tv",
    popularMovies: "movie/popular",
    topRatedMovies: "movie/top_rated",
    upcomingMovies: "movie/upcoming",
    popularSeries: "tv/popular",
    topRatedSeries: "tv/top_rated",
  },
  params: {
    api_key: "3d1d44f45c31beb4fa420771967796c4",
    query: "",
    language: "it",
  },
  error: "",
  loading: false,
  searchedMovieList: [],
  searchedSeriesList: [],
  imagePath: "https://image.tmdb.org/t/p/w342",
  languages: [
    "it",
    "en",
    "hi",
    "ml",
    "zh",
    "fr",
    "es",
    "de",
    "ja",
    "pt",
    "ru",
    "uz",
  ],
  movieFound: true,
  seriesFound: true,
  loading: false,
  page: "welcome",
  jumboTrailers: [
    "https://www.youtube.com/embed/8uJih78e4rY?",
    "https://www.youtube.com/embed/rztd9Kw_D1I?",
    "https://www.youtube.com/embed/hH5NdGyMxxQ?",
    "https://www.youtube.com/embed/Oiz8siG8OXA?",
    "https://www.youtube.com/embed/sXTqxmg8FfU?",
  ],
});
