import { reactive } from "vue";

export const store = reactive({
  apiUrl: "https://api.themoviedb.org/3/",
  endPoint: {
    movie: "search/movie",
    series: "search/tv",
    popularMovies: "movie/popular",
    topRatedMovies: "movie/top_rated",
    upcomingMovies: "movie/upcoming",
    popularSeries: "tv/popular",
    topRatedSeries: "tv/top_rated",
  },
  params: {
    api_key: "3d1d44f45c31beb4fa420771967796c4",
    query: "",
    language: "it",
  },
  error: "",
  loading: false,
  searchedMovieList: [],
  searchedSeriesList: [],
  imagePath: "https://image.tmdb.org/t/p/w342",
  languages: [
    "it",
    "en",
    "hi",
    "ml",
    "zh",
    "fr",
    "es",
    "de",
    "ja",
    "pt",
    "ru",
    "uz",
  ],
  movieFound: true,
  seriesFound: true,
  loading: false,
  page: "welcome",
  jumboTrailers: [
    "https://www.youtube.com/embed/8uJih78e4rY?autoplay=1",
    "https://www.youtube.com/embed/rztd9Kw_D1I?autoplay=1",
    "https://www.youtube.com/embed/hH5NdGyMxxQ?autoplay=1",
    "https://www.youtube.com/embed/Oiz8siG8OXA?autoplay=1",
    "https://www.youtube.com/embed/sXTqxmg8FfU?autoplay=1",
  ],
  users: [
    {
      userName: "Tu",
      userImage: "/public/images/users/you.webp",
    },
    {
      userName: "Bambini",
      userImage: "/public/images/users/Screenshot 2023-11-16 173700.png",
    },
  ],
  avatarArray: [
    "/public/images/users/netflix-profile-pictures-5yup5hd2i60x7ew3.webp",
    "/public/images/users/netflix-profile-pictures-1000-x-1000-w3lqr61qe57e9yt8.webp",
    "/public/images/users/netflix-profile-pictures-1000-x-1000-vnl1thqrh02x7ra2.webp",
    "/public/images/users/netflix-profile-pictures-1000-x-1000-qo9h82134t9nv0j0.webp",
    "/public/images/users/netflix-profile-pictures-1000-x-1000-dyrp6bw6adbulg5b.webp",
    "/public/images/users/netflix-profile-pictures-1000-x-1000-88wkdmjrorckekha.webp",
    "/public/images/users/netflix-profile-pictures-1000-x-1000-62wgyitks6f4l79m.webp",
  ],
  currentUser: {},
});
